// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZeH5tCoHrZtvZ0dNA-BlphA4T4ezH-8',
    appId: '1:621684559425:android:f02034dffb8170948dc0c0',
    messagingSenderId: '621684559425',
    projectId: 'cleaning-app-2ef8a',
    databaseURL: 'https://cleaning-app-2ef8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleaning-app-2ef8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARBpLF7dT4aAM4on-MrvAXdZaGFPCVlRA',
    appId: '1:621684559425:ios:c0396c8f5774217b8dc0c0',
    messagingSenderId: '621684559425',
    projectId: 'cleaning-app-2ef8a',
    databaseURL: 'https://cleaning-app-2ef8a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cleaning-app-2ef8a.appspot.com',
    iosBundleId: 'com.example.firebaseAutentication',
  );

}